using GiveAID.Models;
using Microsoft.EntityFrameworkCore;

namespace GiveAID.Data;

public class AppDbContext(DbContextOptions<AppDbContext> opts): DbContext(opts)
{
    public DbSet<User> Users => Set<User>();
    public DbSet<Ngo> Ngos => Set<Ngo>();
    public DbSet<UserInterest> UserInterests => Set<UserInterest>();
    public DbSet<DonationCause> DonationCauses => Set<DonationCause>();
    public DbSet<WelfareProgramme> WelfareProgrammes => Set<WelfareProgramme>();
    public DbSet<Transaction> Transactions => Set<Transaction>();
    public DbSet<UserQuery> UserQueries => Set<UserQuery>();
    public DbSet<CorporatePartner> CorporatePartners => Set<CorporatePartner>();
    public DbSet<NgoPartner> NgoPartners => Set<NgoPartner>();
    public DbSet<Notification> Notifications => Set<Notification>();
    public DbSet<UserModification> UserModifications => Set<UserModification>();
    public DbSet<AboutUsSubpage> AboutUsSubpages => Set<AboutUsSubpage>();
    public DbSet<Donation> Donations => Set<Donation>();
    public DbSet<GalleryImage> GalleryImages => Set<GalleryImage>();
    
    public IQueryable<User> Members => Users.Where(u => u.Role == UserRole.Member);
    public IQueryable<User> ActiveMembers => Members.Where(u => !u.IsDeleted);
    
    public IQueryable<Ngo> ActiveNgos => Ngos.Where(u => !u.IsDeleted);
    public IQueryable<DonationCause> ActiveDonationCauses => DonationCauses.Where(u => !u.IsDeleted);
    
    public IQueryable<WelfareProgramme> ActiveWelfareProgrammes => WelfareProgrammes.Where(u => !u.IsDeleted);
    public IQueryable<WelfareProgramme> AvailableWelfareProgrammes => ActiveWelfareProgrammes.Where(u => u.StartTime <= DateTimeOffset.UtcNow && (!u.EndTime.HasValue || u.EndTime >= DateTimeOffset.UtcNow));

    public IQueryable<Donation> ValidDonations => Donations.Where(u => u.Status == DonationStatus.Completed);
    
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // Configure Guid primary keys to not be auto-generated by the database
        modelBuilder.Entity<User>().Property(e => e.UserId).ValueGeneratedNever();
        modelBuilder.Entity<Ngo>().Property(e => e.NgoId).ValueGeneratedNever();
        modelBuilder.Entity<DonationCause>().Property(e => e.CauseId).ValueGeneratedNever();
        modelBuilder.Entity<WelfareProgramme>().Property(e => e.ProgrammeId).ValueGeneratedNever();
        modelBuilder.Entity<Transaction>().Property(e => e.TransactionId).ValueGeneratedNever();
        modelBuilder.Entity<UserQuery>().Property(e => e.QueryId).ValueGeneratedNever();
        modelBuilder.Entity<CorporatePartner>().Property(e => e.PartnerId).ValueGeneratedNever();
        modelBuilder.Entity<Notification>().Property(e => e.NotificationId).ValueGeneratedNever();
        modelBuilder.Entity<UserModification>().Property(e => e.ModificationId).ValueGeneratedNever();
        modelBuilder.Entity<AboutUsSubpage>().Property(e => e.SubpageId).ValueGeneratedNever();
        modelBuilder.Entity<Donation>().Property(e => e.DonationId).ValueGeneratedNever();
        modelBuilder.Entity<GalleryImage>().Property(e => e.ImageId).ValueGeneratedNever();

        // UserInterest Relationship
        modelBuilder.Entity<UserInterest>()
            .HasOne(ui => ui.User)
            .WithMany(u => u.UserInterests)
            .HasForeignKey(ui => ui.UserId)
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<UserInterest>()
            .HasOne(ui => ui.Ngo)
            .WithMany(n => n.UserInterests)
            .HasForeignKey(ui => ui.NgoId)
            .OnDelete(DeleteBehavior.Cascade);

        // NgoPartner Relationship
        modelBuilder.Entity<NgoPartner>()
            .HasOne(np => np.Ngo)
            .WithMany(n => n.NgoPartners)
            .HasForeignKey(np => np.NgoId)
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<NgoPartner>()
            .HasOne(np => np.Partner)
            .WithMany(p => p.NgoPartners)
            .HasForeignKey(np => np.PartnerId)
            .OnDelete(DeleteBehavior.Cascade);

        // WelfareProgramme Relationship
        modelBuilder.Entity<WelfareProgramme>()
            .HasOne(wp => wp.Ngo)
            .WithMany(n => n.WelfareProgrammes)
            .HasForeignKey(wp => wp.NgoId)
            .OnDelete(DeleteBehavior.Restrict);

        modelBuilder.Entity<WelfareProgramme>()
            .HasOne(wp => wp.Cause)
            .WithMany(c => c.WelfareProgrammes)
            .HasForeignKey(wp => wp.CauseId)
            .OnDelete(DeleteBehavior.Restrict);

        // Donation Relationship
        modelBuilder.Entity<Donation>()
            .HasOne(d => d.User)
            .WithMany(u => u.Donations)
            .HasForeignKey(d => d.UserId)
            .OnDelete(DeleteBehavior.Restrict);

        modelBuilder.Entity<Donation>()
            .HasOne(d => d.Transaction)
            .WithMany(t => t.Donations)
            .HasForeignKey(d => d.TransactionId)
            .OnDelete(DeleteBehavior.Restrict);

        modelBuilder.Entity<Donation>()
            .HasOne(d => d.Ngo)
            .WithMany(n => n.Donations)
            .HasForeignKey(d => d.NgoId)
            .OnDelete(DeleteBehavior.SetNull);

        modelBuilder.Entity<Donation>()
            .HasOne(d => d.Programme)
            .WithMany(p => p.Donations)
            .HasForeignKey(d => d.ProgrammeId)
            .OnDelete(DeleteBehavior.SetNull);

        modelBuilder.Entity<Donation>()
            .HasOne(d => d.Cause)
            .WithMany()
            .HasForeignKey(d => d.CauseId)
            .OnDelete(DeleteBehavior.SetNull);

        // UserQuery Relationship
        modelBuilder.Entity<UserQuery>()
            .HasOne(uq => uq.User)
            .WithMany(u => u.UserQueries)
            .HasForeignKey(uq => uq.UserId)
            .OnDelete(DeleteBehavior.Restrict);

        // Notification Relationship
        modelBuilder.Entity<Notification>()
            .HasOne(n => n.User)
            .WithMany(u => u.Notifications)
            .HasForeignKey(n => n.UserId)
            .OnDelete(DeleteBehavior.Cascade);

        // UserModification Relationship
        modelBuilder.Entity<UserModification>()
            .HasOne(um => um.User)
            .WithMany(u => u.UserModifications)
            .HasForeignKey(um => um.UserId)
            .OnDelete(DeleteBehavior.SetNull);

        modelBuilder.Entity<UserModification>()
            .HasOne(um => um.Subpage)
            .WithMany(s => s.UserModifications)
            .HasForeignKey(um => um.SubpageId)
            .OnDelete(DeleteBehavior.Cascade);

        // GalleryImage Relationship
        modelBuilder.Entity<GalleryImage>()
            .HasOne(gi => gi.Programme)
            .WithMany(p => p.GalleryImages)
            .HasForeignKey(gi => gi.ProgrammeId)
            .OnDelete(DeleteBehavior.SetNull);
    }
}
