// <auto-generated />
using System;
using GiveAID.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GiveAID.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GiveAID.Models.AboutUsSubpage", b =>
                {
                    b.Property<Guid>("SubpageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("SubpageId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("AboutUsSubpages");
                });

            modelBuilder.Entity("GiveAID.Models.CorporatePartner", b =>
                {
                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("WebsiteLink")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("PartnerId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CorporatePartners");
                });

            modelBuilder.Entity("GiveAID.Models.Donation", b =>
                {
                    b.Property<Guid>("DonationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CauseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("NgoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProgrammeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DonationId");

                    b.HasIndex("CauseId");

                    b.HasIndex("NgoId");

                    b.HasIndex("ProgrammeId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("GiveAID.Models.DonationCause", b =>
                {
                    b.Property<Guid>("CauseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CauseId");

                    b.ToTable("DonationCauses");
                });

            modelBuilder.Entity("GiveAID.Models.GalleryImage", b =>
                {
                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Caption")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid?>("ProgrammeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ImageId");

                    b.HasIndex("ProgrammeId");

                    b.ToTable("GalleryImages");
                });

            modelBuilder.Entity("GiveAID.Models.Ngo", b =>
                {
                    b.Property<Guid>("NgoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Website")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("NgoId");

                    b.ToTable("Ngos");
                });

            modelBuilder.Entity("GiveAID.Models.NgoPartner", b =>
                {
                    b.Property<Guid>("NgoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NgoId", "PartnerId");

                    b.HasIndex("PartnerId");

                    b.ToTable("NgoPartners");
                });

            modelBuilder.Entity("GiveAID.Models.Notification", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("GiveAID.Models.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gateway")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("TransactionTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("GiveAID.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GiveAID.Models.UserInterest", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NgoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "NgoId");

                    b.HasIndex("NgoId");

                    b.ToTable("UserInterests");
                });

            modelBuilder.Entity("GiveAID.Models.UserModification", b =>
                {
                    b.Property<Guid>("ModificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SubpageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ModificationId");

                    b.HasIndex("SubpageId");

                    b.HasIndex("UserId");

                    b.ToTable("UserModifications");
                });

            modelBuilder.Entity("GiveAID.Models.UserQuery", b =>
                {
                    b.Property<Guid>("QueryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplyText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QueryId");

                    b.HasIndex("UserId");

                    b.ToTable("UserQueries");
                });

            modelBuilder.Entity("GiveAID.Models.WelfareProgramme", b =>
                {
                    b.Property<Guid>("ProgrammeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CauseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("MaxDonation")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("NgoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ProgrammeId");

                    b.HasIndex("CauseId");

                    b.HasIndex("NgoId");

                    b.ToTable("WelfareProgrammes");
                });

            modelBuilder.Entity("GiveAID.Models.Donation", b =>
                {
                    b.HasOne("GiveAID.Models.DonationCause", "Cause")
                        .WithMany()
                        .HasForeignKey("CauseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GiveAID.Models.Ngo", "Ngo")
                        .WithMany("Donations")
                        .HasForeignKey("NgoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GiveAID.Models.WelfareProgramme", "Programme")
                        .WithMany("Donations")
                        .HasForeignKey("ProgrammeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GiveAID.Models.Transaction", "Transaction")
                        .WithMany("Donations")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GiveAID.Models.User", "User")
                        .WithMany("Donations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cause");

                    b.Navigation("Ngo");

                    b.Navigation("Programme");

                    b.Navigation("Transaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GiveAID.Models.GalleryImage", b =>
                {
                    b.HasOne("GiveAID.Models.WelfareProgramme", "Programme")
                        .WithMany("GalleryImages")
                        .HasForeignKey("ProgrammeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Programme");
                });

            modelBuilder.Entity("GiveAID.Models.NgoPartner", b =>
                {
                    b.HasOne("GiveAID.Models.Ngo", "Ngo")
                        .WithMany("NgoPartners")
                        .HasForeignKey("NgoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GiveAID.Models.CorporatePartner", "Partner")
                        .WithMany("NgoPartners")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ngo");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("GiveAID.Models.Notification", b =>
                {
                    b.HasOne("GiveAID.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GiveAID.Models.UserInterest", b =>
                {
                    b.HasOne("GiveAID.Models.Ngo", "Ngo")
                        .WithMany("UserInterests")
                        .HasForeignKey("NgoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GiveAID.Models.User", "User")
                        .WithMany("UserInterests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ngo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GiveAID.Models.UserModification", b =>
                {
                    b.HasOne("GiveAID.Models.AboutUsSubpage", "Subpage")
                        .WithMany("UserModifications")
                        .HasForeignKey("SubpageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GiveAID.Models.User", "User")
                        .WithMany("UserModifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Subpage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GiveAID.Models.UserQuery", b =>
                {
                    b.HasOne("GiveAID.Models.User", "User")
                        .WithMany("UserQueries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GiveAID.Models.WelfareProgramme", b =>
                {
                    b.HasOne("GiveAID.Models.DonationCause", "Cause")
                        .WithMany("WelfareProgrammes")
                        .HasForeignKey("CauseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GiveAID.Models.Ngo", "Ngo")
                        .WithMany("WelfareProgrammes")
                        .HasForeignKey("NgoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cause");

                    b.Navigation("Ngo");
                });

            modelBuilder.Entity("GiveAID.Models.AboutUsSubpage", b =>
                {
                    b.Navigation("UserModifications");
                });

            modelBuilder.Entity("GiveAID.Models.CorporatePartner", b =>
                {
                    b.Navigation("NgoPartners");
                });

            modelBuilder.Entity("GiveAID.Models.DonationCause", b =>
                {
                    b.Navigation("WelfareProgrammes");
                });

            modelBuilder.Entity("GiveAID.Models.Ngo", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("NgoPartners");

                    b.Navigation("UserInterests");

                    b.Navigation("WelfareProgrammes");
                });

            modelBuilder.Entity("GiveAID.Models.Transaction", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("GiveAID.Models.User", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("Notifications");

                    b.Navigation("UserInterests");

                    b.Navigation("UserModifications");

                    b.Navigation("UserQueries");
                });

            modelBuilder.Entity("GiveAID.Models.WelfareProgramme", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("GalleryImages");
                });
#pragma warning restore 612, 618
        }
    }
}
